### ISSUE TITLE
mac-gpu-miner-1.0.1 crash

### ISSUE THREAD

**Issue by val3riefr** [garrylachman/mac-gpu-miner#3]
Hi, the mac-gpu-miner-1.0.1 is crashing on Mac Big Sur 11.2.3
it can't open...any solution or update?

**Comment by garrylachman** [comment]
Can you add more info?
* When its crash, on start or when start mining?
* Is there some message or error you see?

Open terminal and run 
`/Applications/macgpuminer.app/Contents/MacOS/macgpuminer`
send please the output you see in terminal, this command should print stdout & stderr log.

**Comment by val3riefr** [comment]
it chrash when i want to open the app. it says "macgpuminer can not open due to a problem
Check with the developer that macgpuminer can work with this version of MacOS …"
is it settled for Mac Big Sur?

here what the terminal files says

Last login: Sun Jul 11 11:15:07 on ttys000
/Applications/macgpuminer.app/Contents/MacOS/macgpuminer ; exit;                
valerietoumayan@Pro-de-Valerie ~ % /Applications/macgpuminer.app/Contents/MacOS/macgpuminer ; exit;
dyld: Library not loaded: /usr/local/opt/libmicrohttpd/lib/libmicrohttpd.12.dylib
  Referenced from: /Applications/macgpuminer.app/Contents/Frameworks/libxmrstak_opencl_backend.dylib
  Reason: image not found
zsh: abort      /Applications/macgpuminer.app/Contents/MacOS/macgpuminer
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...       4 completed.

[Opération terminée]

**Comment by garrylachman** [comment]
do you have homebrew? try 
`brew install libmicrohttpd`

**Comment by val3riefr** [comment]
i didn't have homebrew, after checking their website i run terminal with this comand 
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
afther that do i enter your comand? and then .. ?

**Comment by garrylachman** [comment]
after you install homebrew (i suggest you to learn more about it - its the right way to install on mac). 
run `brew install libmicrohttpd` - this command will install the missing library..

from your log:
`Library not loaded: /usr/local/opt/libmicrohttpd/lib/libmicrohttpd.12.dyli`

**Comment by val3riefr** [comment]
thanks, what's next after "brew install libmicrohttpd" ?
sorry i'm new at this..

**Comment by garryvelotix** [comment]
after that try to open the application, of its still not working post here the log like before.

if its still not working try:
```
sudo mkdir -p /usr/local/opt/libmicrohttpd/lib/
sudo link /opt/homebrew/lib/libmicrohttpd.12.dylib  /usr/local/opt/libmicrohttpd/lib/libmicrohttpd.12.dylib
```

and one more thing - its not going to work on Apple M1 CPU. Its compiled for intel CPU

**Comment by simtechnos** [comment]
Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: F2DC58FA-E869-380A-8C1E-53D831FB3F9E
Library not loaded: /usr/local/opt/hwloc/lib/libhwloc.15.dylib
  Referenced from: /Applications/macgpuminer.app/Contents/Frameworks/libxmrstak_opencl_backend.dylib
  Reason: image not found

**Comment by aliawadh980** [comment]
This worked for me:
`brew install hwloc`

**Comment by simtechnos** [comment]
thanks this works now.
